import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./ui/home/navbar";


export const metadata: Metadata = {
  title: "Gilcllys Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
